### ISSUE TITLE
Not marked as adaptive

### ISSUE THREAD

**Issue by janvlug** [SeaDve/Breathing#12]
Please mark Breathing as adaptive, so that it shows up as adaptive in GNOME Software. Currently it is marked as Desktop Only:

![image](https://user-images.githubusercontent.com/5903208/163690419-ccecaf1a-bc46-4d71-acea-24adb643fbb9.png)

**Comment by SeaDve** [comment]
This seems to be fixed now:

![image](https://github.com/SeaDve/Breathing/assets/64297935/380af56a-989c-4195-8ef8-edfbda7ad59e)
