### ISSUE TITLE
[Feature Request] [Project Proposal] Breathing & Gnome Shell Integration

### ISSUE THREAD

**Issue by okwalerie** [SeaDve/Breathing#15]
I know this project is GPLv3, but I figured I'd ask here for feedback. I love having this breathing app as "Always on Top" and "Always on Visible Workspace", but it gets in the way sometimes. I've been getting started with GNOME Extension development, and felt like this would work great with some integration with GNOME Shell.

Would people be interested in a GNOME Extension inspired by Breathing? I understand that there's not too much to add/modify, as it's best kept simple. However, if I reuse the source code for this (e.g. animation, maybe synchronizing the timer so it can be tabbed away from), then potential bug fixes may feed back into this project.

Or, should they be left separate? Thoughts, musings on interesting features, etc, all appreciated.

**Comment by SeaDve** [comment]
Feel free to modify or copy the code as long as it is within GPLv3 terms. 

I would like to mention though that Breathing's animation and timer code is very hacky and not very extensible. I did have plans on major refactoring, but haven't got that time yet.

> Would people be interested in a GNOME Extension inspired by Breathing?

That would be interesting and some people might like it, but other people tends to keep gnome-shell extensions at the minimum.

**Comment by sojusnik** [comment]
@weavermarquez 
> I know this project is GPLv3, but I figured I'd ask here for feedback. I love having this breathing app as "Always on Top" and "Always on Visible Workspace", but it gets in the way sometimes. I've been getting started with GNOME Extension development, and felt like this would work great with some integration with GNOME Shell.

That's an awesome idea! I was looking for a "Always on Top" and "Always on Visible Workspace" solution as well, but couldn't find one that meets essential criteria.

> Would people be interested in a GNOME Extension inspired by Breathing?

Definitely! Let me know if you're still interested. I would like to share with you some of my observations and suggestions.

**Comment by SeaDve** [comment]
Closing this as not planned for now
