### ISSUE TITLE
Switching to dark mode removes rounded corners.

### ISSUE THREAD

**Issue by AbrarSL** [SeaDve/Breathing#8]
![Screenshot from 2021-10-23 00-43-15](https://user-images.githubusercontent.com/69783006/138510914-ec535f98-22ce-4405-996c-c43351b68ef6.png)

![Screenshot from 2021-10-23 00-43-18](https://user-images.githubusercontent.com/69783006/138510937-bb13cefb-8406-4879-b00c-0830cbdd53c7.png)

**Comment by SeaDve** [comment]
this shall be fixed when we move to a newer version of libadwaita
